### ISSUE TITLE
Print Delivery Note Material

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/OpenPrint#4]
@ekachandrasetiawan : 
- [x] Di print out Delivery note yang baru di bagian Material field description tidak terprint,, seharusnya muncul
- [x] Notes belum muncul

**Comment by lajayuhniyarsyah** [comment]
![image](http://snag.gy/PoN7p.jpg)

**Comment by lajayuhniyarsyah** [comment]
![Image PN dn](http://snag.gy/jwTis.jpg)
- [x]

**Comment by lajayuhniyarsyah** [comment]
> Notes juga belum muncul

**Comment by ekachandrasetiawan** [comment]
Sudah OK 

File GIT
https://github.com/lajayuhniyarsyah/OpenPrint/commit/cd496199574a32d4e5d8f44ed59db226d97cc640
