### ISSUE TITLE
Report Quotation

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/OpenPrint#6]
[report.xlsx](https://github.com/lajayuhniyarsyah/OpenPrint/files/146264/report.xlsx)

**Comment by lajayuhniyarsyah** [comment]
@hendri30 : please comment link yang sudah dibikin apa aja.

**Comment by hendri30** [comment]
sale-order/report-quotation
sale-order/year-summary-quotation
sale-order/detail-summary-quotation
sale-order/sales-amount-status

delivery-note/reportkpi
delivery-note/year-summary-kpi

**Comment by lajayuhniyarsyah** [comment]
[report.xlsx](https://github.com/lajayuhniyarsyah/OpenPrint/files/168329/report.xlsx)

Terlampir update report xlsx

**Comment by lajayuhniyarsyah** [comment]
- [ ] @hendri30 : Pada tab Penjualan Product By Category tolong buat cart line nya
