### ISSUE TITLE
Print DN - Tanda tangan

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/OpenPrint#67]
Print DN ada tanda tangan hasil commit 2132a90758caa06430e498619f1259452e7d9f2b menurut laporan user tidak pas di kolom tanda tangan
- [x] Tanda tangan tidak pas pada kolom nya (Per User masing masing)
- [x] User Sri
- [x] User Hadi
- [x] User Mike
- [x] User Novri

**Comment by ekachandrasetiawan** [comment]
untuk MIKE dan Novri Belum di coba
