### ISSUE TITLE
Bug - Print OP User Novri

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/OpenPrint#68]
User Novri pada saat print OP bagian tanda tangannya turun ke halaman ke 2

Please follow up,, dan fixing bug nya

Jangan lupakan user lain,, jadi mohon di cek juga apa user lain kena effek baik sebelum dibenerin dan sesudahnya ?

**Comment by ekachandrasetiawan** [comment]
Masalah ada pada settingan default user novri

Sudah OK

**Comment by lajayuhniyarsyah** [comment]
Ok Fixed
