### ISSUE TITLE
Font Print Out Purchase Order Problem

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/OpenPrint#95]
Pada print out purchase order ada font yang di load di internet,,, sejak minggu kemarin font tersebut tidak terapply di print out, pease cek

**Comment by ekachandrasetiawan** [comment]
Dalam Hal ini, Ko Willam sudah instal font yang dibutuhkan
dan untuk dapat terbaca font. user harus logout terlebih dahulu
